create table category
(
    id   integer generated by default as identity
        primary key,
    name varchar(255)
);

alter table category
    owner to postgres;

create table person
(
    id                   integer generated by default as identity
        primary key,
    birthday             text not null,
    date_time_of_created timestamp,
    email                text not null
        constraint uk_fwmwi44u55bo4rvwsv0cln012
            unique,
    firstname            text not null,
    lastname             text not null,
    login                varchar(50),
    password             varchar(255),
    patronymic           text,
    phone_number         text not null
        constraint uk_2ldqhx89sy06ya51rrnndhwmc
            unique,
    role                 varchar(255)
);

alter table person
    owner to postgres;

create table product
(
    id                   integer generated by default as identity
        primary key,
    date_time_of_created timestamp,
    description          text         not null,
    price                real         not null
        constraint product_price_check
            check (price >= (1)::double precision),
    seller               varchar(255) not null,
    title                text         not null
        constraint uk_qka6vxqdy1dprtqnx9trdd47c
            unique,
    warehouse            varchar(255) not null,
    category_id          integer      not null
        constraint fk1mtsbur82frn64de7balymq9s
            references category
);

alter table product
    owner to postgres;

create table image
(
    id         integer generated by default as identity
        primary key,
    file_name  varchar(255),
    product_id integer not null
        constraint fkgpextbyee3uk9u6o2381m7ft1
            references product
);

alter table image
    owner to postgres;

create table orders
(
    id         integer generated by default as identity
        primary key,
    count      integer not null,
    date_time  timestamp,
    number     varchar(255),
    price      real    not null,
    status     integer,
    person_id  integer not null
        constraint fk1b0m4muwx1t377w9if3w6wwqn
            references person,
    product_id integer not null
        constraint fk787ibr3guwp6xobrpbofnv7le
            references product
);

alter table orders
    owner to postgres;

create table product_cart
(
    id         integer generated by default as identity
        primary key,
    person_id  integer
        constraint fksgnkc1ko2i1o9yr2p63ysq3rn
            references person,
    product_id integer
        constraint fkhpnrxdy3jhujameyod08ilvvw
            references product
);

alter table product_cart
    owner to postgres;


